repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: cargo-check
    -   id: fmt
        args: ['--', '--verbose']
    -   id: clippy
-   repo: local
    hooks:
      - id: cargo-test
        name: cargo-test
        entry: cargo
        args: [ test  ]
        language: system
        files: ".+.rs$"
        pass_filenames: false
